apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
    template:
      metadata:
        labels:
          app: front-end
        spec:
          containers:
            - name: front-end
              # add your image later !!!!!!!
              image: "tsawler/front-end:1.0.1"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              env:
                name: BROKER_URL
                value: "http://broker-service.info"
              # it doesn't do anything , its just informal
              ports:
                - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      name: main-port
      port: 8081
      targetPort: 8081