apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
    template:
      metadata:
        labels:
          app: mongo
        spec:
          containers:
            - name: mongo
              image: "tsawler/logger-service:1.0.1"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              # it doesn't do anything , its just informal
              ports:
                - containerPort: 80
                - containerPort: 5001
                - containerPort: 50001
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: tcp
      name: web-port
      port: 80
      targetPort: 80
    - protocol: tcp
      name: rpc-port
      port: 5001
      targetPort: 5001
    - protocol: tcp
      name: grpc-port
      port: 50001
      targetPort: 50001